# Generated by Django 3.0.6 on 2021-07-24 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luckydragon_app', '0003_auto_20210724_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='guestorder',
            name='guest_order_card_cvv',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='guestorder',
            name='guest_order_card_exp_date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='guestorder',
            name='guest_order_card_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guestorder',
            name='guest_order_card_zipcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='guestorder',
            name='guest_order_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guestorder',
            name='guest_order_street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guestorder',
            name='guest_order_street_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='guestorder',
            name='guest_order_zipcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luckydragon_app.Card'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_detail_options',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
