# Generated by Django 3.0.6 on 2021-07-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydragon_app', '0004_auto_20210724_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_price',
            field=models.FloatField(default=0),
        ),
    ]
