# Generated by Django 3.1.4 on 2021-08-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydragon_app', '0007_auto_20210820_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_spicy',
            field=models.BooleanField(default=False),
        ),
    ]
