# Generated by Django 3.1.4 on 2021-08-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydragon_app', '0008_food_food_spicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestorder',
            name='guest_order_tip',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='guestorder',
            name='guest_order_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_tip',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_detail_price',
            field=models.FloatField(),
        ),
    ]
