# Generated by Django 3.1.4 on 2021-08-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydragon_app', '0010_auto_20210826_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestorder',
            old_name='uest_order_timestamp',
            new_name='guest_order_timestamp',
        ),
        migrations.RemoveField(
            model_name='guestorder',
            name='guest_order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='guestorder',
            name='guest_order_delivery_fee',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_delivery_fee',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='guestorder',
            name='guest_order_tip',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_tip',
            field=models.FloatField(null=True),
        ),
    ]
