# Generated by Django 3.1.4 on 2021-10-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luckydragon_app', '0012_auto_20210829_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_apt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='guestorder',
            name='guest_order_apt',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
